version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    command: --lower_case_table_names=1
    volumes:
      - ./data/mysql/:/var/lib/mysql

networks:
  default:
    driver: bridge